service: workflow-engine

image: 0x63616c/the-workflow-engine

ssh:
  user: calum

servers:
  web:
    hosts:
      - homelab
    options:
      add-host: host.docker.internal:host-gateway

proxy:
  host: homelab
  ssl: false
  app_port: 4301

registry:
  server: ghcr.io
  username: "0x63616c"
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  remote: ssh://calum@homelab
  arch: arm64
  args:
    BUILD_HASH: <%= `git rev-parse --short HEAD`.strip %>

env:
  clear:
    NODE_ENV: production
    PORT: "4301"
    PORT_OFFSET: "0"
    INNGEST_DEV: "0"
    HA_URL: "http://host.docker.internal:8123"
  secret:
    - INNGEST_EVENT_KEY
    - INNGEST_SIGNING_KEY
    - HA_TOKEN

accessories:
  inngest:
    image: inngest/inngest
    cmd: inngest start
    host: homelab
    port: "8388:8288"
    options:
      network: kamal
    env:
      secret:
        - INNGEST_EVENT_KEY
        - INNGEST_SIGNING_KEY

volumes:
  - data:/app/data
