display_information:
  name: Evee
  description: The best bot! <3
  background_color: "#000000"
features:
  assistant_view:
    assistant_description: Evee is a friendly assistant for the World Wide Webb workspace.
    suggested_prompts: []
  bot_user:
    display_name: Evee
    always_online: true
oauth_config:
  scopes:
    bot:
      - chat:write
      - chat:write.public
      - chat:write.customize
      - channels:read
      - channels:history
      - channels:manage
      - channels:join
      - channels:write.invites
      - channels:write.topic
      - groups:read
      - groups:history
      - groups:write
      - groups:write.invites
      - im:read
      - im:history
      - im:write
      - mpim:read
      - mpim:history
      - mpim:write
      - reactions:read
      - reactions:write
      - pins:read
      - pins:write
      - bookmarks:read
      - bookmarks:write
      - files:read
      - files:write
      - users:read
      - users:read.email
      - users.profile:read
      - users:write
      - app_mentions:read
      - assistant:write
      - commands
      - links:read
      - links:write
      - metadata.message:read
      - canvases:read
      - canvases:write
      - calls:read
      - calls:write
      - workflows.templates:write
      - conversations.connect:manage
      - conversations.connect:read
      - conversations.connect:write
      - dnd:read
      - emoji:read
      - team:read
      - usergroups:read
      - usergroups:write
      - reminders:read
      - reminders:write
    user:
      - channels:history
      - channels:read
      - channels:write
      - chat:write
      - emoji:read
      - files:read
      - files:write
      - groups:history
      - groups:read
      - groups:write
      - im:history
      - im:read
      - im:write
      - links:read
      - mpim:history
      - mpim:read
      - mpim:write
      - pins:read
      - pins:write
      - reactions:read
      - reactions:write
      - reminders:read
      - reminders:write
      - search:read
      - users:read
      - users:read.email
      - users.profile:read
      - users.profile:write
      - dnd:read
      - dnd:write
      - identify
      - stars:read
      - team:read
  pkce_enabled: false
settings:
  event_subscriptions:
    bot_events:
      - app_mention
      - message.im
      - assistant_thread_started
      - assistant_thread_context_changed
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
